
image: cypress/base:10


stages:
    - test


test:
  stage: test
  before_script:
    - npm install http-server -g
    - npm install -g wait-on
    - npm install cypress

  script:
    - npx cypress run --record --key e129aa95-d4c7-46d8-a7a5-907fde71e413

