tests:
  image: cypress/base:10
  cache:
    paths:
      - node_modules/
  stage:
      - install
      - test

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  before_script:
    - npm install http-server -g
    - npm install cypress
    - npm run start:server
    - npm run start
  script:
    -npx cypress run --record --key e129aa95-d4c7-46d8-a7a5-907fde71e413

